### ISSUE TITLE
Forgot password broken

### ISSUE THREAD

**Issue by mikaoj** [schibsted/sdk-ios#16]
1. browserRedirectForgotPassword seems to be broken.
It generates an invalid url.

2. If I remove the client_id parameter from the url, it works and opens in safari. However, I never get a callback to my app with the url scheme that I set up.
Is it suppose to open the app after a successful forgot password request have been done? Or was that just wishful thinking from me?

**Comment by mikaoj** [comment]
You can try for yourself in your native app example

**Comment by oskarh** [comment]
1. This works for me in the native client with our test client. What does your url look like and which client are you using?

2. Did you register your redirect uri? The redirect is supposed to redirect the user back to the login screen.

Could you send an email to support@spid.no including your logs and what client you're using?
