### ISSUE TITLE
handleOpenURL

### ISSUE THREAD

**Issue by mikaoj** [schibsted/sdk-ios#17]
From your documentation:
// This returns YES if SPiD SDK handled the URL
return [[SPiDClient sharedInstance] handleOpenURL:url];

But if we take a look at handleOpenURL:
```objc
- (BOOL)handleOpenURL:(NSURL *)url {
    SPiDDebugLog(@"SPiDSDK received url: %@", [url absoluteString]);
    NSString *redirectURLString = [[self redirectURI] absoluteString];
    NSString *urlString = [[[url absoluteString] componentsSeparatedByString:@"?"] objectAtIndex:0];

    if ([urlString hasPrefix:redirectURLString] && _completionHandler) {
        if ([urlString hasSuffix:@"login"]) {
            // Assert
            return [self doHandleOpenURL:url];
        } else if ([urlString hasSuffix:@"logout"]) {
            return [self doHandleOpenURL:url];
        } else if ([urlString hasSuffix:@"failure"]) {
            return [self doHandleOpenURL:url];
        }
    }

    return NO;
}
```

We can see that it requires a completion block to check if it can handle the url. Otherwise it will return NO, even if it is a spid url.
Fix for now is to use - (BOOL)handleOpenURL:(NSURL *)url completionHandler:(void (^)(SPiDError *response))completionHandler;

**Comment by oskarh** [comment]
Sorry for the late response.

Updated the documentation to better reflect how it behaves, thanks for pointing it out.
