### ISSUE TITLE
Tag and push 2.0

### ISSUE THREAD

**Issue by mikaoj** [schibsted/sdk-ios#23]
git tag 2.0
git push --tags

pod trunk push

:)

**Comment by m4c1ek** [comment]
+1

**Comment by mikael-lindstrom** [comment]
Since we are using semver, we should name the tag 2.0.0

**Comment by mikaoj** [comment]
2 month later...
You've taged the version, nice! 👍
But you still need to push the new podspec to cocoapods.

I've sad it to a bunch of people within the organisation, I would be happy to maintain this sdk and take care of stuff like this ^^

**Comment by danielbentes** [comment]
@mikaoj You are welcomed to help us maintain this SDK!

**Comment by mikaoj** [comment]
Done 😀
