### ISSUE TITLE
Should probably be a category instead of subclass.

### ISSUE THREAD

**Issue by jnutting** [schibsted/sdk-ios#5]
The only reason you need to subclass NSError is to add properties/ivars or override functionality. You aren't overriding anything, just adding new methods, and the "descriptions" property you've added isn't necessary: That's exactly what NSError's userInfo is for. NSError is uniquely designed to be able to accommodate 3rd-party error data using the separation of domain, code, and userInfo.

Instead, all of these should probably be in a category on NSError. For safety's sake, should preferably use a prefix for the method names, e.g. "spidErrorFromJSONData:" instead of "errorFromJSONData:"

The reason this is an issue is simple: interoperation with other NSError instances. If I'm writing code that's passing an NSError** through multiple blocks at different levels, I shouldn't have to worry about the class of an error that appears. In a current project, I am forced to use isKindOfClass: at one point (since in the case of a SPIDError I want to print the contents of "descriptions" instead of the standard userInfo), which is an ugly workaround.

The key thing, which extends beyond this class itself, is this: The public APIs of all the SPID stuff should expose NSError, not SPIDError. No client code should have to know about your special error class. If you insist on using a subclass, you should still make all APIs use NSError instead, *and* you should go the full mile and at least override NSError's description methods so that client code can get a nice description of the spid errors.

**Comment by mikaoj** [comment]
Thanks for the feedback!
This is fixed as of 2.0.0
