### ISSUE TITLE
documentation - setup, custom url

### ISSUE THREAD

**Issue by micjaesc** [schibsted/sdk-ios#6]
Please, update wiki documentation http://schibsted.github.io/sdk-ios/setting-up-spid.html about properties for custom-url-schemes 

Some steps, which I think are missing, and will safe time for others.

"...
Open the project in Xcode and click on its XYZ-Info.plist file to open it in the Standard Editor. Right-click the top row’s Information Property List and select Add Row
A row will be added and you’ll be prompted to select a key from a drop-down menu. Scroll to the bottom and select “URL types”
This will create an array key item, so click the disclosure triangle next to “URL types” to expand it.

Click on Item 0 to expand it to show the URL identifier line. The value for this can actually be anything, but it’s normal to use the Bundle Identifier, so double-click the Bundle Identifier value to select it and then copy the identifier string. Then double-click the field to the right of the URL identifier and paste it into the box.

Now right-click on Item 0, and select Add Row. You’ll be presented with a shorter drop-down of possible values; this time select URL Schemes. This will create an array key item. Expand it, double-click the value box for its Item 0, and enter Your custom URL scheme...."

Inspired by https://www.inkling.com/read/learning-ios-programming-alasdair-allan-2nd/chapter-12/custom-url-schemes

BR
Michal

**Comment by oskarh** [comment]
Hi Michal,

Sorry for the latest reply ever.

I added instructions about this in our new (and still very incomplete unfortunately) docs for iOS.

Thanks for your contribution!
